### PR TITLE
Fixed issues search page

### PR DESCRIPTION
**Pull request by GiusyMancuso**

### CODE REVIEW

**Comment by GiusyMancuso** [comment]
[SearchFragment - format code](https://trello.com/c/5XBmuHYl/11-searchfragment-format-code)

**Comment by GiusyMancuso** [comment]
[SearchFragment - Empty view](https://trello.com/c/KK3iziJU/13-searchfragment-empty-view)

**Comment by GiusyMancuso** [comment]
[SearchFragment - onAdapterClick](https://trello.com/c/EW0Tw4Nl/14-searchfragment-onadapterclick)

**Review by alessiodicorato — APPROVED** [review]

**Comment by alessiodicorato** [comment]
[SearchFragment - setOnQueryTextListener](https://trello.com/c/d1hOOnpY/12-searchfragment-setonquerytextlistener)

**Pull request merged**
